<?php

// 用于控制显示的字段
$header_list = [
	'priority',
	'chrom',
	'pos',
	'ref',
	'alt',
	'rsid',
	'genename',
	'aachange',
	'func',
  
	'novo_wes_an',
	'novo_wes_af',
	'novo_wes_hom_af',
	'novo_wes_het_af',
	'novo_wes_hwe',
	'novo_wes_dp_mean',
	'novo_wes_dp_percentile',
	'novo_wes_ad_mean',
	'novo_wes_ad_percentile',
	'novo_wgs_an',
	'novo_wgs_af',
	'novo_wgs_hom_af',
	'novo_wgs_het_af',
	'novo_wgs_hwe',
	'novo_wgs_dp_mean',
	'novo_wgs_dp_percentile',
	'novo_wgs_ad_mean',
	'novo_wgs_ad_percentile',

	'chinese_1000g',
	'all_1000g',
	'eas_1000g',
	'gnomad_all_af',
	'gnomad_all_an',
	'gnomad_eas_af',
	'gnomad_eas_an',
	'esp6500si_all',

	'description',
	'gene',
	'genedetail',
	'exonicfunc',
	'gencode',
	'cpgislandext',
	'cytoband',
	'wgrna',
	'targetscans',
	'tfbsconssites',
	'genomicsuperdups',
	'repeat',
	'clinvar',
	'gwascatalog',
	'dbscsnv_score',
	'spidex',
	'interpro_domain',
	'sift',
	'polyphen2_hvar',
	'polyphen2_hdiv',
	'mutationtaster',
	'lrt',
	'mutationassessor',
	'fathmm',
	'siphy_29way_logodds',
	'phylop46way_placental',
	'phylop100way_vertebrate',
	'cadd',
	'gerp_gt2',
	'mcap',
	'omim',
	'hgmd_disease_id',
	'hgmd_mutation_url',
	'gwas_pubmed_pvalue',
	'pubmedid',
	'go_bp',
	'go_cc',
	'go_mf',
	'kegg_pathway',
	'pid_pathway',
	'biocarta_pathway',
	'reactome_pathway',
	'expression_summary',
	'expression_visual_link',
	'rna_tissue_category',
	'tissue_with_max_fpkm',
	'subcellular_location',

  // 'novo_wes_ref_samples',
  // 'novo_wes_hom_samples',
  // 'novo_wes_het_samples',
  // 'novo_wgs_ref_samples',
  // 'novo_wgs_hom_samples',
  // 'novo_wgs_het_samples',

];
// print_r($header_list);

// 为特殊字段增加href链接
$href_maps = [
  'genename' => 'https://www.genecards.org/Search/Keyword?queryString=',
  'rsid' => 'https://www.ncbi.nlm.nih.gov/projects/SNP/snp_ref.cgi?rs=',
  'omim' => 'https://www.omim.org/entry/'
];
// print_r($href_maps);

?>